[package]
name = "payload"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"

[dependencies.windows-sys]
version = "0.60"
features = [
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
]

[profile.release]
panic = "abort"
opt-level="z"

[[bin]]
name = "payload"
path = "payload.rs"
