CC = {{CC}}
LD = {{LD}}
EXE_PAYLOAD_CFLAGS = -fPIC -mconsole -Os
#-D_UCRT: Do not use mingw's version of the C runtime, but use Microsoft's implementation.
#-DWINBASEAPI: Do not import from DLLs, but statically
BIN_PAYLOAD_CFLAGS = \
 -Os\
 -fPIC\
 -nostdlib\
 -nostartfiles\
 -ffreestanding\
 -fno-asynchronous-unwind-tables\
 -fno-ident\
 -Wl,--no-seh\
 -fno-optimize-sibling-calls\
 -ffunction-sections\
 -D_UCRT= \
 -DWINBASEAPI=
LD_FLAGS = \
	--gc-sections # Included even though it doesn't seem to work

loader.exe: loader.c
	${CC} $^ -o $@

loader.c: loader.j2.c payload.bin
	shellcode_compiler template $< PAYLOAD=@payload.bin > $@

payload.bin: linker.ld payload.o winlib.o AdjustStack.o
	${LD} -T $^ -o $@ ${LD_FLAGS}

# Compile payload C code to object file
payload.o: payload.c
	${CC} -c $^ -o $@ ${BIN_PAYLOAD_CFLAGS}

# Determine undefined references based on linking errors
functions.txt: linker.ld payload.o AdjustStack.o
	${LD} -T $^ -o /dev/null ${LD_FLAGS} 2>&1 | awk -F\` '/undefined reference/{print substr($$(NF), 1, length($$(NF))-1)}' > $@

winlib.c: winlib.j2.c functions.txt
	shellcode_compiler winlib $^ > $@

winlib.o: winlib.c
	${CC} -c $^ -o $@ ${BIN_PAYLOAD_CFLAGS}

AdjustStack.o: AdjustStack.s
	${CC} -c $^ -o $@ ${BIN_PAYLOAD_CFLAGS}

exe: payload.exe

payload.exe: winlib.o payload.o
	${CC} $^ -o $@ ${EXE_PAYLOAD_CFLAGS}

